app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('industrial', ['uses'=>'HomeController@industrial', 'as'=>'industrial']);

Route::group(['prefix'=>'admin'], function(){

	Route::get('/', function() {
		if (Auth::guest()) {
			return redirect()->to('/admin/auth/login');
		}

		else {
			return redirect()->route('admin.dashboard');
		}
	});

	Route::get('dashboard', ['uses'=>'HomeController@admin', 'as'=>'admin.dashboard']);

	Route::get('/items/search', ['uses'=>'ItemsController@search', 'as'=>'admin.items.search']);
	Route::resource('items', 'ItemsController');
	Route::get('/items/{id}/delete', ['uses'=>'ItemsController@destroy', 'as'=>'admin.items.destroy']);

	Route::resource('users', 'UsersController');
	Route::get('/users/{id}/delete', ['uses'=>'UsersController@destroy', 'as'=>'admin.users.destroy']);

	Route::get('/themes/search', ['uses'=>'ThemesController@search', 'as'=>'admin.themes.search']);
	Route::resource('themes', 'ThemesController');
	Route::get('/themes/{id}/delete', ['uses'=>'ThemesController@destroy', 'as'=>'admin.themes.destroy']);

	Route::resource('products', 'ProductsController');
	Route::get('/products/{id}/delete', ['uses'=>'ProductsController@destroy', 'as'=>'admin.products.destroy']);

	Route::get('/roles/permissions', ['uses'=>'RolesController@editPermissions', 'as'=>'admin.permissions.edit']);
	Route::post('/roles/permissions', ['uses'=>'RolesController@updatePermissions', 'as'=>'admin.permissions.update']);
	Route::resource('roles', 'RolesController');

	Route::controllers([
		'auth' => 'Auth\AuthController',
		'password' => 'Auth\PasswordController',
	]);


});

Route::post('/products/save', ['uses'=>'ProductsController@store', 'as'=>'products.store']);

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword, EntrustUserTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'email',
		'password',
		'first_name',
		'last_name',
		'middle_initial',
		'photo_path',
		'address_1',
		'address_2',
		'contact_num',
		'status'
	];

	protected $appends = ['role'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	public function getRoleAttribute()
	{
		if (!$this->roles->isEmpty())
			return $this->roles()->first()->id;
	}

	public function getMiddleInitialAttribute($value)
	{
		// Append period if there isn't
		if (!empty($value) && !preg_match('/(\w+)\.$/', $value))
			return trim($value).'.';

		return $value;
	}

	public function getFullNameAttribute()
	{
		$fullName = $this->first_name . ' ';

		if (isset($this->middle_initial))
			$fullName .= $this->middle_initial . ' ';

		$fullName .= $this->last_name;

		return trim($fullName);
	}

	public function getStatusValueAttribute()
	{
		if ($this->status == 0)
			return 'Inactive';

		return 'Active';
	}

}

app/Http/Controllers/UsersController.php
<?php namespace App\Http\Controllers;

use App\User;
use App\UserInfo;
use App\Role;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Auth\Registrar;
use Illuminate\Contracts\Auth\Guard;

use Illuminate\Http\Request;

class UsersController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		// Hide superadmin
		$users = User::with('roles')->where('id', '!=', 1)->paginate(10);

		return view('users.index', compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$user = null;
		$roles = Role::all()->lists('name', 'id');
		return view('users.create', compact('user', 'roles'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Requests\StoreUserRequest $request, Registrar $registrar, Guard $auth)
	{
		$input = $request->all();

		$validator = $registrar->validator($input);

		if ($validator->fails())
		{
			$this->throwValidationException(
				$request, $validator
			);
		}

		$user = $registrar->create($input);

		if ($photo = array_pull($input, 'photo')) {
			$folder = '/uploads/users/photos/';
			$filename = $user->id . '.' . $photo->getClientOriginalExtension();
			$path = $folder . $filename;
			$photo->move(public_path($folder), $filename);

			$user->photo_path = $path;
			$user->save(); // Update user with photo
		}


		$user->roles()->sync($request->only('role'));

		return redirect()->route('admin.users.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$user = User::with('roles')->find($id);

		return view('users.show', compact('user'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		// Block editing of superadmin
		if ($id == 1) {
			abort(403, 'Nice try.');
		}

		$user = User::find($id)->load(['roles']);
		$roles = Role::all()->lists('name', 'id');
		return view('users.edit', compact('user', 'roles'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Requests\UpdateUserRequest $request)
	{
		$user = User::with('roles')->find($id);

		$input = $request->all();

		if (empty($input['password']) && empty($input['password_confirmation'])) {
			array_pull($input, 'password');
		} else {
			$input['password'] = bcrypt($input['password']);
		}

		$user->update($input);
		$user->roles()->sync($request->only('role'));

		if ($photo = array_pull($input, 'photo')) {
			$folder = '/uploads/users/photos/';
			$filename = $id . '.' . $photo->getClientOriginalExtension();
			$path = $folder . $filename;
			$photo->move(public_path($folder), $filename);

			$user->photo_path = $path;
			$user->save(); // Update user with photo
		}

		return redirect()->route('admin.users.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		User::find($id)->delete();

		return redirect()->route('admin.users.index');
	}

}

resources/views/users/create.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">ADD USER</div>

				<div class="panel-body">

                    @include('errors.list')

                    {!! Form::open([ 'route' => 'admin.users.store', 'files' => 'true', 'class' => 'form-horizontal']) !!}
						@include('users.form')
					    <div class="col-md-4 col-md-offset-4">
					        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
					    	<a href="{{ route('admin.users.index') }}" class="btn btn-primary">Cancel</a>
					    </div>
                    {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">EDIT USER</div>

				<div class="panel-body">


                    @include('errors.list')

                    {!! Form::model($user, [ 'method' => 'PATCH', 'route' => [ 'admin.users.update', $user ], 'files' => 'true', 'class' => 'form-horizontal' ]) !!}
						@include('users.form')
					    <div class="col-md-4 col-md-offset-4">
					        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
					    	<a href="{{ route('admin.users.show', [$user]) }}" class="btn btn-primary">Cancel</a>
					    </div>
                    {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/users/form.blade.php
<div class="row">
    <fieldset>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="email">Email</label>
      <div class="col-md-4">
      {!! Form::text('email', null, ['class'=>'form-control input-md', 'required']) !!}
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="password">Password</label>
      <div class="col-md-4">
      {!! Form::input('password', 'password', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="password_confirmation">Confirm Password</label>
      <div class="col-md-4">
      {!! Form::input('password', 'password_confirmation', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- Select Basic -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="type">Role</label>
      <div class="col-md-4">
            {!! Form::select('role', [''=>'Please Select']+$roles, null, [ 'class' => 'form-control' ] ) !!}
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="first_name">First Name</label>
      <div class="col-md-4">
      {!! Form::text('first_name', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="middle_initial">Middle Initial</label>
      <div class="col-md-4">
      {!! Form::text('middle_initial', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="last_name">Last Name</label>
      <div class="col-md-4">
      {!! Form::text('last_name', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- File Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="photo">Photo</label>
      <div class="col-md-4">
        @if (isset($user['photo_path']))
          <img src="{{ asset($user['photo_path']) }}" style="max-width: 100%; margin-bottom: 1em;" />
        @endif
        <input id="photo" name="photo" class="input-file" type="file" />
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="address_1">Address</label>
      <div class="col-md-4">
      {!! Form::text('address_1', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <div class="col-md-4 col-md-offset-4">
      {!! Form::text('address_2', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="contact_num">Contact Number</label>
      <div class="col-md-4">
      {!! Form::text('contact_num', null, ['class'=>'form-control input-md']) !!}
      </div>
    </div>

    <!-- Multiple Radios (inline) -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="status">Status</label>
      <div class="col-md-4">
        <label class="radio-inline">
          {!! Form::radio('status', 1, null) !!}
          Active
        </label>
        <label class="radio-inline">
          {!! Form::radio('status', 0, null) !!}
          Inactive
        </label>
      </div>
    </div>

    </fieldset>

</div>

resources/views/users/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
            {!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">USER MANAGEMENT</div>

				<div class="panel-body">


                    <div class="row paging">
                        <div class="col-md-6">
                            {!! $users->render() !!}
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="{{ route('admin.users.create') }}" class="btn btn-primary">Add User</a>
                        </div>
                    </div>

                    <table class="table table-responsive">
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>Name</th>
                            <th>Role</th>
                            <th>Status</th>
                            <th></th>
                        </tr>

                        @foreach ($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->full_name }}</td>
                            <td>{{ $user->roles->first()->name or '' }}</td>
                            <td>{{ $user->status_value }}</td>
                            <td class="text-right">
                                <a href="{{ route('admin.users.show', [$user]) }}" class="btn btn-default btn-xs"
                                   data-toggle="tooltip" data-placement="top" title="View">
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                </a>
                                <a href="{{ route('admin.users.edit', [$user]) }}" class="btn btn-default btn-xs"
                                   data-toggle="tooltip" data-placement="top" title="Edit">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                                <a href="{{ route('admin.users.destroy', [$user]) }}" class="btn btn-default btn-xs btn-danger delete-confirm"
                                   data-toggle="tooltip" data-placement="top" title="Delete" data-item="user">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            </td>
                        </tr>
                        @endforeach

                    </table>
                    <div class="row paging">
                        <div class="col-md-6">
                            {!! $users->render() !!}
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="{{ route('admin.users.create') }}" class="btn btn-primary">Add User</a>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render() !!}
                <div class="panel panel-default">
                    <div class="panel-heading">VIEW USER</div>

                    <div class="panel-body">
                        <div class="row">
                            @if (empty($user->photo_path))
                            <div class="col-xs-12">
                            @else
                            <div class="col-xs-8">
                            @endif
                                <table class="table table-striped">
                                    <tr>
                                        <td>Name:</td>
                                        <td>{{ $user->full_name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Role:</td>
                                        <td>{{ $user->roles->first()->name or '' }}</td>
                                    </tr>
                                    <tr>
                                        <td>Address:</td>
                                        <td>
                                            <p>{{ $user->address_1 }}</p>
                                            @if (isset($user->address_2))
                                                <p>{{ $user->address_2 }}</p>
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Contact Number:</td>
                                        <td>{{ $user->contact_num }}</td>
                                    </tr>
                                    <tr>
                                        <td>Status:</td>
                                        <td>{{ $user->status_value }}</td>
                                    </tr>
                                </table>
                            </div>
                            @if (!empty($user->photo_path))
                            <div class="col-xs-4">
                                    <img src="{{ asset($user->photo_path) }}" style="max-width: 100%">
                            </div>
                            @endif
                            <div class="col-xs-12">
                                <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary">Edit</a>
                                <a href="{{ route('admin.users.index') }}" class="btn btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection