app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('industrial', ['uses'=>'HomeController@industrial', 'as'=>'industrial']);

Route::group(['prefix'=>'admin'], function(){

	Route::get('/', function() {
		if (Auth::guest()) {
			return redirect()->to('/admin/auth/login');
		}

		else {
			return redirect()->route('admin.dashboard');
		}
	});

	Route::get('dashboard', ['uses'=>'HomeController@admin', 'as'=>'admin.dashboard']);

	Route::get('/items/search', ['uses'=>'ItemsController@search', 'as'=>'admin.items.search']);
	Route::resource('items', 'ItemsController');
	Route::get('/items/{id}/delete', ['uses'=>'ItemsController@destroy', 'as'=>'admin.items.destroy']);

	Route::resource('users', 'UsersController');
	Route::get('/users/{id}/delete', ['uses'=>'UsersController@destroy', 'as'=>'admin.users.destroy']);

	Route::get('/themes/search', ['uses'=>'ThemesController@search', 'as'=>'admin.themes.search']);
	Route::resource('themes', 'ThemesController');
	Route::get('/themes/{id}/delete', ['uses'=>'ThemesController@destroy', 'as'=>'admin.themes.destroy']);

	Route::resource('products', 'ProductsController');
	Route::get('/products/{id}/delete', ['uses'=>'ProductsController@destroy', 'as'=>'admin.products.destroy']);

	Route::get('/roles/permissions', ['uses'=>'RolesController@editPermissions', 'as'=>'admin.permissions.edit']);
	Route::post('/roles/permissions', ['uses'=>'RolesController@updatePermissions', 'as'=>'admin.permissions.update']);
	Route::resource('roles', 'RolesController');

	Route::controllers([
		'auth' => 'Auth\AuthController',
		'password' => 'Auth\PasswordController',
	]);


});

Route::post('/products/save', ['uses'=>'ProductsController@store', 'as'=>'products.store']);

app/Item.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Http\Traits\LookupsValue as LookupsValue;
use Nicolaslopezj\Searchable\SearchableTrait;

class Item extends Model {

	use LookupsValue;
	use SearchableTrait;

	protected $fillable = [
		'item_id',
		'description',
		'type',
		'texture_path',
		'background_color',
		'price'
	];

	protected $appends = ['type_name'];

	protected $searchable = [
		'columns' => [
			'item_id' => 10,
			'description' => 5,
			'price' => 5
		]
	];

	public function properties()
	{
		return $this->hasMany('App\ItemProperty');
	}

	public function getTypeNameAttribute()
	{
		if (isset($this->attributes['type']))
			return $this->getLookupValue('item_type', $this->attributes['type']);
	}

	public function themes()
	{
		return $this->belongsToMany('App\Theme');
	}

	public function products()
	{
		return $this->belongsToMany('App\Product');
	}

}

app/Http/Controllers/ItemsController.php
<?php namespace App\Http\Controllers;

use App\Item;
use App\ItemProperty;
use App\Theme;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Auth\Registrar;
use Illuminate\Contracts\Auth\Guard;

use Illuminate\Http\Request;
use Storage;
use Image;

class ItemsController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$items = Item::paginate(10);

		return view('items.index', compact('items'));
	}


	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function search(Request $request)
	{
		$query = $request->input('q');
		$items = Item::search($query)->paginate(10);
		$request->flash();

		return view('items.index', compact('items', 'query'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$data['itemTypesList'] = $this->lookupSelect('item_type');
		$data['themesList'] = Theme::get()->lists('name', 'id');
		$data['itemThemes'] = null;
		return view('items.create', $data);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param StoreItemRequest
	 * @return Response
	 */
	public function store(Requests\StoreItemRequest $request)
	{
		$input = $request->all();

		$item = Item::create($input);

		if (isset($input['themes']))
			$item->themes()->sync($input['themes']);

		// Save image and get thumbnail
		// todo: set thumbnail based on item type
		if ($texture = array_pull($input, 'texture')) {
			$folder = '/uploads/items/textures/';
			$filename = $item->id . '.' . $texture->getClientOriginalExtension();
			$path = $folder . $filename;
			// if ($texture->getClientOriginalExtension() != 'svg') {
			// 	$thumbnail = Image::make($texture)->fit(50)
			// 						->save(public_path($folder) . 'thumbnail_' . $item->id . '.jpg');
			// }
			$texture->move(public_path($folder), $filename);

			$item->texture_path = $path;
			$item->save(); // Update item with path
		}

		if (isset($input['properties'])) {
			foreach ($input['properties'] as $key => $value) {
				$item->properties()->save(new ItemProperty([
					'key' => $key,
					'value' => $value
				]));
			}
		}

		return redirect()->route('admin.items.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$item = Item::find($id)->load(['properties', 'themes']);
		return view('items.show', compact('item'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['itemTypesList'] = $this->lookupSelect('item_type');
		$data['themesList'] = Theme::all()->lists('name', 'id');
		$item = Item::find($id)->load(['properties', 'themes']);

		$data['itemThemes'] = $item->themes->lists('id');

		$item = $item->toArray();
		// Unserialize properties
		foreach (array_pull($item, 'properties') as $property) {
			$item['properties'][$property['key']] = $property['value'];
		}

		$data['item'] = $item;

		return view('items.edit', $data);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Requests\UpdateItemRequest $request)
	{
		$item = Item::with(['properties', 'themes'])->find($id);
		$input = $request->all();

		// Save image and get thumbnail
		// todo: set thumbnail based on item type
		if ($texture = array_pull($input, 'texture')) {
			$folder = '/uploads/items/textures/';
			$filename = $item->id . '.' . $texture->getClientOriginalExtension();
			$path = $folder . $filename;
			// if ($texture->getClientOriginalExtension() != 'svg') {
			// 	$thumbnail = Image::make($texture)->fit(50)
			// 						->save(public_path($folder) . 'thumbnail_' . $item->id . '.jpg');
			// }
			$texture->move(public_path($folder), $filename);

			$item->texture_path = $path;
			$item->save(); // Update item with path
		}

		if (isset($input['themes']))
			$item->themes()->sync($input['themes']);

		$item->update($input);

		if (!$item->properties->isEmpty())
			$item->properties()->delete();

		if (isset($input['properties'])) {
			foreach ($input['properties'] as $key => $value) {
				$item->properties()->save(new ItemProperty([
					'key' => $key,
					'value' => $value
				]));
			}
		}

		return redirect()->route('admin.items.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Item::find($id)->delete();

		return redirect()->route('admin.items.index');
	}

}

resources/views/items/create.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">ADD ITEM</div>

				<div class="panel-body">

                    @include('errors.list')

                    {!! Form::open([ 'route' => 'admin.items.store', 'files' => 'true', 'class' => 'form-horizontal']) !!}
						@include('items.form')
					    <div class="col-md-4 col-md-offset-4">
					        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
					    	<a href="{{ route('admin.items.index') }}" class="btn btn-primary">Cancel</a>
					    </div>
                    {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/items/edit.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">EDIT ITEM</div>

				<div class="panel-body">

                    @include('errors.list')

                    {!! Form::model($item, [ 'method' => 'PATCH', 'files'=>'true', 'route' => [ 'admin.items.update', $item["id"] ], 'class' => 'form-horizontal']) !!}
						@include('items.form')
						<div class="col-md-4 col-md-offset-4">
					        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
					    	<a href="{{ route('admin.items.show', [$item['id']]) }}" class="btn btn-primary">Cancel</a>
					    </div>
                    {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/items/form.blade.php
<link href="{{ asset('/admin-assets/css/bootstrap-colorpicker.min.css') }}"  rel="stylesheet">
<script src="{{ asset('/admin-assets/js/bootstrap-colorpicker.min.js') }}"></script>
<div class="row">
    <fieldset>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="item_id">Item ID</label>
      <div class="col-md-4">
      {!! Form::text('item_id', null, ['class'=>'form-control input-md', 'required']) !!}
      </div>
    </div>

    <!-- Select Basic -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="type">Item Type</label>
      <div class="col-md-4">
        {!! Form::select('type', [''=>'Please Select']+$itemTypesList, null, ['class'=>'form-control', 'required', 'id'=>'type']) !!}
      </div>
    </div>

    <script type="text/javascript">
    $(function() {
      var $materials = $('#materials'),
          $soles = $('#soles'),
          $print = $('#print'),
          $type = $('#type');

      var updateProperties = function() {

        switch($type.val()) {
          case '1': // Strap
            $materials.find('.radio:not(.strap)').hide();
            $materials.find('.strap').show().find('input').prop('disabled', false);
            $soles.slideUp();
            $print.slideUp();
            $materials.slideDown();
            break;
          case '2': // Sole
            $materials.find('.radio:not(.sole)').hide();
            $materials.find('.sole').show().find('input').prop('disabled', false);
            $materials.slideDown();
            $print.slideUp();
            $soles.slideDown();
            $soles.find('input').prop('disabled', false);
            break;
          case '3': // Print
            $materials.slideUp();
            $soles.slideUp();
            $print.slideDown();
            $print.find('input').prop('disabled', false);
            break;
          default:
            $materials.slideUp();
            $soles.slideUp();
            $print.slideUp();
        } // switch

      } // update

        $('#type').change(function(e) {
          resetInputs();
          updateProperties();
        });

      var resetInputs = function() {
        $('#materials, #soles, #print').find('input').prop('disabled', true);
      }


      // Initialize
      resetInputs();
      updateProperties();

    });

    </script>

    <!-- Textarea -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="description">Description</label>
      <div class="col-md-4">
      {!! Form::textarea('description', null, ['class'=>'form-control']) !!}
      </div>
    </div>

    <!-- File Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="texture">Texture</label>
      <div class="col-md-4">
        @if (isset($item['texture_path']))
          <img src="{{$item['texture_path']}}" style="max-width: 100%; margin-bottom: 1em;" />
        @endif
        <input id="texture" name="texture" class="input-file" type="file" />
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="background_color">Background Color</label>
      <div class="col-md-4">
        <div class="input-group bgcolor">
        {!! Form::text('background_color', null, ['class'=>'form-control input-md']) !!}
          <span class="input-group-addon"><i style="border: 1px solid #cccccc"></i></span>
        </div>
      </div>
      <script>
          $(function(){
              $('.bgcolor').colorpicker();
          });
      </script>
    </div>

    <!-- Textarea -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="price">Price</label>
      <div class="col-md-4">
      {!! Form::text('price', null, ['class'=>'form-control']) !!}
      </div>
    </div>

    <!-- Multiple Radios (inline) -->
    <div class="form-group" id="print" style="display: none;">
      <label class="col-md-4 control-label" for="properties[vacuum_print]">Vacuum Print</label>
      <div class="col-md-4">
        <label class="checkbox-inline">
          {!! Form::hidden('properties[vacuum_print]', 0, null, ['disabled']) !!}
          {!! Form::checkbox('properties[vacuum_print]', 1, null, ['disabled']) !!}
          Yes
        </label>
      </div>
    </div>

    <!-- Multiple Radios -->
    <div class="form-group" id="materials" style="display: none;">
      <label class="col-md-4 control-label" for="properties[material_type]">Type of Material</label>
      <div class="col-md-4">
      <div class="radio strap">
        <label>
          {!! Form::radio('properties[material_type]', 'Rubber') !!}
          Rubber
        </label>
        </div>
      <div class="radio sole">
        <label>
          {!! Form::radio('properties[material_type]', 'EVA') !!}
          EVA
        </label>
        </div>
      <div class="radio strap sole">
        <label>
          {!! Form::radio('properties[material_type]', 'PVC') !!}
          PVC
        </label>
        </div>
      </div>
    </div>

    <!-- Multiple Radios (inline) -->
    <div class="form-group" id="soles" style="display: none;">
      <label class="col-md-4 control-label" for="properties[sole]">Sole</label>
      <div class="col-md-4">
        <label class="radio-inline">
          {!! Form::radio('properties[sole]', 'Insole', null, ['disabled']) !!}
          Insole
        </label>
        <label class="radio-inline">
          {!! Form::radio('properties[sole]', 'Outsole', null, ['disabled']) !!}
          Outsole
        </label>
      </div>
    </div>

    <!-- Select Multiple -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="themes">Themes</label>
      <div class="col-md-4">
        {!! Form::select('themes', $themesList, $itemThemes, ['class'=>'form-control', 'id'=>'themes', 'name'=>'themes[]', 'multiple']) !!}
      </div>
    </div>



    </fieldset>

</div>

resources/views/items/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
            {!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">ITEM MANAGEMENT</div>
				<div class="panel-body">

                    <div class="row paging">
                        <div class="col-md-6">
                            @if (isset($query))
                                {!! $items->appends(['q'=>$query])->render() !!}
                            @else
                                {!! $items->render() !!}
                            @endif
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="{{ route('admin.items.create') }}" class="btn btn-primary">Add Item</a>
                        </div>
                    </div>

                    <div id="custom-search-input" class="paging">
                        {!! Form::open([ 'method' => 'GET', 'route' => 'admin.items.search' ]) !!}
                        <div class="input-group col-md-12">
                        {!! Form::text('q', null, ['class'=>'form-control input-xs', 'placeholder'=>'Search items']) !!}
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-xs" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </span>
                        </div>
                        {!! Form::close() !!}
                    </div>

                    @if ($items->isEmpty())
                        <p class="alert alert-danger">No items found</p>
                    @else

                    <table class="table table-responsive">
                        <tr>
                            <th>ID</th>
                            <th>Type</th>
                            <th>Texture</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th></th>
                        </tr>

                        @foreach ($items as $item)
                        <tr>
                            <td>{!! $item['item_id'] !!}</td>
                            <td>{!! $item['type_name'] !!}</td>
                            <td><img src="{{ asset($item['texture_path']) }}" width="50" height="50"></td>
                            <td><p>{!! $item['description'] !!}</p></td>
                            <td><p>{!! $item['price'] !!}</p></td>
                            <td class="text-right">
                                <a href="{{ route('admin.items.show', [$item]) }}" class="btn btn-default btn-xs"
                                    data-toggle="tooltip" data-placement="top" title="View">
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                </a>
                                <a href="{{ route('admin.items.edit', [$item]) }}" class="btn btn-default btn-xs"
                                    data-toggle="tooltip" data-placement="top" title="Edit">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                                <a href="{{ route('admin.items.destroy', [$item]) }}" class="btn btn-default btn-xs btn-danger delete-confirm"
                                        data-toggle="tooltip" data-placement="top" title="Delete">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            </td>
                        </tr>

                        @endforeach
                    </table>
                    @endif

                    <div class="row paging">
                        <div class="col-md-6">
                            @if (isset($query))
                                {!! $items->appends(['q'=>$query])->render() !!}
                            @else
                                {!! $items->render() !!}
                            @endif
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="{{ route('admin.items.create') }}" class="btn btn-primary">Add Item</a>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/items/show.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render() !!}
                <div class="panel panel-default">
                    <div class="panel-heading">VIEW ITEM</div>

                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-12">
                                <h2>{{ $item['type_name'] }}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Texture:</h4>
                                <p class="text-center">
                                    <img src="{{$item['texture_path']}}" style="max-width: 100%;">
                                </p>
                            </div>
                            <div class="col-md-6">
                                <h4>Item ID:</h4>
                                <p>{{ $item['item_id'] }}</p>
                                <h4>Price:</h4>
                                <p>{{ $item['price'] }}</p>
                                <h4>Item properties:</h4>
                                <dl class="dl-horizontal">
                                    @foreach ($item['properties'] as $property)
                                        <dt>{{ $property['key_name'] }}</dt>
                                        <dd>{{ $property['value'] }}</dd>
                                    @endforeach
                                </dl>
                                <h4>Themes:</h4>
                                <ul>
                                    @foreach ($item['themes'] as $theme)
                                    <li>
                                        <a href="{{ route('admin.themes.show', [$theme['id']]) }}">
                                            {{ $theme['name'] }}
                                        </a>
                                    </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 text-right">
                                <a href="{{ route('admin.items.edit', [$item['id']]) }}" class="btn btn-primary">Edit</a>
                                <a href="{{ route('admin.items.index') }}" class="btn btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection