app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('industrial', ['uses'=>'HomeController@industrial', 'as'=>'industrial']);

Route::group(['prefix'=>'admin'], function(){

	Route::get('/', function() {
		if (Auth::guest()) {
			return redirect()->to('/admin/auth/login');
		}

		else {
			return redirect()->route('admin.dashboard');
		}
	});

	Route::get('dashboard', ['uses'=>'HomeController@admin', 'as'=>'admin.dashboard']);

	Route::get('/items/search', ['uses'=>'ItemsController@search', 'as'=>'admin.items.search']);
	Route::resource('items', 'ItemsController');
	Route::get('/items/{id}/delete', ['uses'=>'ItemsController@destroy', 'as'=>'admin.items.destroy']);

	Route::resource('users', 'UsersController');
	Route::get('/users/{id}/delete', ['uses'=>'UsersController@destroy', 'as'=>'admin.users.destroy']);

	Route::get('/themes/search', ['uses'=>'ThemesController@search', 'as'=>'admin.themes.search']);
	Route::resource('themes', 'ThemesController');
	Route::get('/themes/{id}/delete', ['uses'=>'ThemesController@destroy', 'as'=>'admin.themes.destroy']);

	Route::resource('products', 'ProductsController');
	Route::get('/products/{id}/delete', ['uses'=>'ProductsController@destroy', 'as'=>'admin.products.destroy']);

	Route::get('/roles/permissions', ['uses'=>'RolesController@editPermissions', 'as'=>'admin.permissions.edit']);
	Route::post('/roles/permissions', ['uses'=>'RolesController@updatePermissions', 'as'=>'admin.permissions.update']);
	Route::resource('roles', 'RolesController');

	Route::controllers([
		'auth' => 'Auth\AuthController',
		'password' => 'Auth\PasswordController',
	]);


});

Route::post('/products/save', ['uses'=>'ProductsController@store', 'as'=>'products.store']);

app/Role.php
<?php namespace App;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
	protected $fillable = ['name'];

	/**
	* Check permission
	*
	* @return boolean
	* @author Gat
	**/
	public function can($permission)
	{
		return in_array($permission->id, $this->perms->lists('id'));
	}
}

app/Http/Controllers/RolesController.php
<?php namespace App\Http\Controllers;

use App\Role;
use App\Permission;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Auth\Registrar;
use Illuminate\Contracts\Auth\Guard;

use Illuminate\Http\Request;

class RolesController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$roles = Role::get()->toArray();

		return view('roles.index', compact('roles'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$role = null;
		return view('roles.create', compact('role'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$role = Role::create($request->all());

		return redirect()->route('admin.roles.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$role = Role::find($id);

		return view('roles.show', compact('role'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$role = Role::find($id)->toArray();

		return view('roles.edit', compact('role'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Request $request)
	{
		$role = Role::find($id);
		$role->update($request->all());

		return redirect()->route('admin.roles.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Role::find($id)->delete();

		return redirect()->route('admin.roles.index');
	}


	/**
	 * List all permissions
	 *
	 * @return Response
	 */
	public function editPermissions()
	{
		$roles = Role::all()->load('perms');
		$permissions = Permission::all();

		return view('roles.permissions', compact('roles', 'permissions'));
	}

	public function updatePermissions(Request $request)
	{
		foreach ($request['permissions'] as $role => $permissions) {
			Role::whereName($role)->first()->perms()->sync($permissions);
		}

		return redirect()->back()->with('message', 'Successfully updated role permissions')
								->with('alert-class', 'success');
	}

}

resources/views/roles/create.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">ADD ROLE</div>

				<div class="panel-body">

                    @include('errors.list')

                    {!! Form::open([ 'route' => 'admin.roles.store' ]) !!}
						@include('roles.form')
					    <div class="col-xs-12 text-right">
					        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
					    	<a href="{{ route('admin.roles.index') }}" class="btn btn-primary">Cancel</a>
					    </div>
                    {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/roles/edit.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">EDIT ROLE</div>

				<div class="panel-body">

                    @include('errors.list')

                    {!! Form::model($role, [ 'method' => 'PATCH', 'route' => [ 'admin.roles.update', $role["id"] ] ]) !!}
						@include('roles.form')

					    <div class="col-xs-12 text-right">
					        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
					    	<a href="{{ route('admin.roles.show', [$role['id']]) }}" class="btn btn-primary">Cancel</a>
					    </div>

                    {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/roles/form.blade.php
<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

resources/views/roles/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
            {!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">ROLE ACCESS MANAGEMENT</div>

				<div class="panel-body">
                    <table class="table table-responsive">
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th></th>
                        </tr>

                        @foreach ($roles as $role)
                        <tr>
                            <td>{{ $role['id']  }}</td>
                            <td>{{ $role['name']  }}</td>
                            <td class="text-right">
                                <a href="{{ route('admin.roles.show', [$role['id']]) }}" class="btn btn-default btn-xs">View</a>
                                <a href="{{ route('admin.roles.edit', [$role['id']]) }}" class="btn btn-default btn-xs">Edit</a>
                                <a href="{{ route('admin.roles.destroy', [$role['id']]) }}" class="btn btn-default btn-xs btn-danger">Delete</a>
                            </td>
                        </tr>
                        @endforeach

                    </table>
                    <div class="pull-right">
                        <a href="{{ route('admin.permissions.edit') }}" class="btn btn-primary">Manage permissions</a>
                        <a href="{{ route('admin.roles.create') }}" class="btn btn-primary">Add Role</a>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/roles/permissions.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render() !!}
                <div class="panel panel-default">
                    <div class="panel-heading">EDIT PERMISSIONS</div>

                    <div class="panel-body">
                        <div class="row">
                            {!! Form::open() !!}
                            <div class="col-xs-12">
                                @if(Session::has('message'))
                                <div class="alert alert-{{ Session::get('alert-class', 'info') }}">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    {{ Session::get('message') }}
                                </div>
                                @endif
                                <table class="table table-striped">
                                    <thead>
                                        <th style="width: 25%;">Permissions</th>
                                        @foreach ($roles as $role)
                                        <th style="text-align: center; width: {!!75/$roles->count()!!}%;">{!! $role->name !!}</th>
                                        @endforeach
                                    </thead>
                                    <tbody>
                                        @foreach ($permissions as $permission)
                                        <tr>
                                            <td style="font-size: 1.1em">{!! $permission->display_name !!}</td>
                                            @foreach ($roles as $index => $role)
                                            <td style="text-align: center;">
                                                {!! Form::checkbox("permissions[$role->name][{$permission->id}]", $permission->id, $role->can($permission)) !!}
                                            </td>
                                            @endforeach
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-xs-12">
                                <div class="pull-right">
                                    <button type="submit" class="btn btn-success">Save</button>
                                    <a href="{{ route('admin.roles.index') }}" class="btn btn-primary">Back</a>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/show.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render() !!}
                <div class="panel panel-default">
                    <div class="panel-heading">VIEW ROLE</div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <table class="table table-striped">
                                    <tr>
                                        <td>Name:</td>
                                        <td>{{ $role->name }}</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-xs-12 text-right">
                                <a href="{{ route('admin.roles.edit', [$role->id]) }}" class="btn btn-primary">Edit</a>
                                <a href="{{ route('admin.roles.index') }}" class="btn btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection